monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.usb-KTMicro_KT02H20_HIFI_Audio.*"
      }
    ]
    actions = {
      update-props = {
        audio.format        = "S32LE"
        api.alsa.period-size = 512
        api.alsa.headroom   = 256
        node.pause-on-idle  = false
      }
    }
  }
]
