monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_input.usb-KTMicro_KT02H20_HIFI_Audio_2020-02-20-0000-0000-0000-00.pro-input-0"
      }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  }
]
