windowrule {
    name = windowrule_1
    match:class = ^([Mm]pv|vlc)$
    tag = +multimedia_video
}
windowrule {
    name = windowrule_2
    match:class = ^(nm-applet|nm-connection-editor|blueman-manager|org.gnome.FileRoller)$
    tag = +settings
}
windowrule {
    name = windowrule_3
    match:class = ^(org.gnome.DiskUtility|wihotspot(-gui)?)$
    tag = +settings
}
windowrule {
    name = windowrule_4
    match:class = ^(org.gnome.SystemMonitor)$ # system monitor
    tag = +viewer
}
windowrule {
    name = windowrule_5
    match:class = ^(org.gnome.Evince)$ # document viewer 
    tag = +viewer
}
windowrule {
    name = windowrule_6
    match:class = ^(eog|org.gnome.Loupe)$ # image viewer
    tag = +viewer
}
